### ISSUE TITLE
"hostname -A" not available on Mac

### ISSUE THREAD

**Issue by robinandeer** [arteria-project/arteria-provisioning#31]
The full error:

```
TASK: [arteria | get ansible's local hostname, used for address rewriting on  test deployment] ***
failed: [stackstorm-master -> 127.0.0.1] => {"changed": true, "cmd": ["hostname", "-A"], "delta": "0:00:00.006993", "end": "2015-10-16 10:39:33.204090", "rc": 1, "start": "2015-10-16 10:39:33.197097", "warnings": []}
stderr: hostname: illegal option -- A
usage: hostname [-fs] [name-of-host]

FATAL: all hosts have already failed -- aborting
```

**Comment by johandahlberg** [comment]
Any ideas for how to solve this? PRs welcome!

**Comment by johanherman** [comment]
~~Perhaps Ansible's `inventory_hostname` will work. I'll have to take a look that it will be OK downstreams as well first though.~~

Strike that.

**Comment by johandahlberg** [comment]
@robinandeer Maybe you want to confirm that this is fixed?

**Comment by robinandeer** [comment]
I'll give it another go!

**Comment by robinandeer** [comment]
Update: everything works smootly (after restarting the webui) :+1: 

It's looking good, getting errors related to integration tests tho:

``` python
TASK: [arteria_node | running integration tests for runfolder...] *************
failed: [testarteria1] => {"changed": true, "cmd": "sleep 2 && /usr/local/bin/runfolder-ws-test", "delta": "0:00:02.286310", "end": "2015-10-19 09:02:03.191856", "rc": 1, "start": "2015-10-19 09:02:00.905546", "warnings": []}
stderr: EEEEE
======================================================================
ERROR: test_can_change_log_level (rest_tests.RestApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/arteria/arteria-runfolder/tests/integration/rest_tests.py", line 31, in setUp
    lambda: line_count('./runfolder.log'), self, 0.1)
  File "/opt/arteria/arteria-runfolder-env/lib/python2.7/site-packages/arteria/testhelpers.py", line 80, in __init__
    self._last = self._func()
  File "/arteria/arteria-runfolder/tests/integration/rest_tests.py", line 31, in <lambda>
    lambda: line_count('./runfolder.log'), self, 0.1)
  File "/arteria/arteria-runfolder/tests/integration/rest_tests.py", line 26, in line_count
    for _ in open(path).xreadlines():
IOError: [Errno 2] No such file or directory: './runfolder.log'
```

``` python
TASK: [arteria_node | running integration tests for bcl2fastq...] *************
failed: [testarteria1] => {"changed": true, "cmd": "sleep 2 && /usr/local/bin/bcl2fastq-ws-test", "delta": "0:00:02.265725", "end": "2015-10-19 09:14:05.554470", "rc": 1, "start": "2015-10-19 09:14:03.288745", "warnings": []}
stderr: E
======================================================================
ERROR: Failure: OSError (No such file /arteria/arteria-bcl2fastq/tests/integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/arteria/arteria-bcl2fastq-env/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /arteria/arteria-bcl2fastq/tests/integration
```

**Comment by withrocks** [comment]
I'm working on a fix for the runfolder service integration tests, pull request probably merged today.

**Comment by johandahlberg** [comment]
Not all the service have fully functional integration tests running at this point, but we'll get there eventually... 

I'm going to go ahead and close this issue now. :smile:
