### ISSUE TITLE
Integration tests failing while running "vagrant up"

### ISSUE THREAD

**Issue by brainstorm** [arteria-project/arteria-provisioning#38]
```
TASK: [arteria_node | running integration tests for runfolder...] *************
failed: [testarteria1] => {"changed": true, "cmd": "sleep 2 && /usr/local/bin/runfolder-ws-test", "delta": "0:00:02.159198", "end": "2015-10-20 14:17:53.460982", "rc": 1, "start": "2015-10-20 14:17:51.301784", "warnings": []}
stderr: E
======================================================================
ERROR: Failure: OSError (No such file /arteria/arteria-runfolder/tests/integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/arteria/arteria-runfolder-env/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /arteria/arteria-runfolder/tests/integration

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
...ignoring
```

```
TASK: [arteria_node | running integration tests for bcl2fastq...] *************
failed: [testarteria1] => {"changed": true, "cmd": "sleep 2 && /usr/local/bin/bcl2fastq-ws-test", "delta": "0:00:02.178175", "end": "2015-10-20 14:27:13.785949", "rc": 1, "start": "2015-10-20 14:27:11.607774", "warnings": []}
stderr: E
======================================================================
ERROR: Failure: OSError (No such file /arteria/arteria-bcl2fastq/tests/integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/arteria/arteria-bcl2fastq-env/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /arteria/arteria-bcl2fastq/tests/integration

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
...ignoring
```

```
TASK: [arteria_node | running integration tests for siswrap...] ***************
failed: [testarteria1] => {"changed": true, "cmd": "sleep 2 && /usr/local/bin/siswrap-ws-test", "delta": "0:00:02.559144", "end": "2015-10-20 14:27:40.164566", "rc": 1, "start": "2015-10-20 14:27:37.605422", "warnings": []}
stdout: ============================= test session starts ==============================
platform linux2 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /arteria/arteria-siswrap, inifile:
plugins: cov, flakes, cache, tornado
collected 0 items / 1 errors

==================================== ERRORS ====================================
_______________ ERROR collecting tests/integration/rest_tests.py _______________
/arteria/arteria-siswrap/tests/integration/rest_tests.py:5: in <module>
    from siswrap.configuration import ConfigurationService
E   ImportError: No module named configuration
=========================== 1 error in 0.23 seconds ============================
...ignoring
```

**Comment by withrocks** [comment]
Hi, thanks for this!

We are aware of these and they will be fixed. The first one (runfolder) was fixed in a change merged earlier today.

**Comment by brainstorm** [comment]
Are you sure? I checked out the provisioning repo quite recently if you refer to the commits from 2h ago... a `.travis.yml` integration would be soo handy here :)

**Comment by withrocks** [comment]
Yes, it would be excellent to have this under continuous integration :) The included repos do have Travis set up though.

I haven't looked into if we could do that for this one, since travis would have to run Vagrant provisioning. Do you know if Travis supports firing up Vagrant machines?

But I'm pretty sure that the runfolder stuff was fixed with the commit merged at ~15:20 today. I'm not as sure if you got latest after that :)

**Comment by brainstorm** [comment]
You can go crazy with this one:

http://www.lewuathe.com/blog/2015/01/25/vagrant-in-travisci/

But I would recommend having a different deploy strategy for TravisCI
(docker, for instance)... Ok, nevermind, close the issue, we'll see if it
passes or not during next build(s) at the workshop tomorrow ;)

**Comment by withrocks** [comment]
Cool. It's not unlikely that we change this to docker either way.

But I'll keep the issue open still, we haven't fixed all of these errors.

**Comment by johandahlberg** [comment]
Also @brainstorm the workshop is on Thursday... If you turn up here tomorrow we won't throw you out, but it is the wrong day. :p

**Comment by brainstorm** [comment]
Lol, thanks, you saved both me and @guillermo-carrasco an unnecessary trip to Uppsala ;P

**Comment by brainstorm** [comment]
Still fails with today's pull :/
